@startuml

state 中台业务说明 {

    [*] --> 代付款 : 提交

    代付款 --> 已取消 : 取消(所有类型)

    代付款 --> 待发货 : 支付(商城)

    代付款 --> 已完成 : 支付(乐园、自主收银)

    待发货 --> 已取消 : 取消(商城)

    待发货 --> 待收货 : 发货(商城)

    待收货 --> 已取消 : 取消(商城)

    待收货 --> 已完成 : 收货(商城)

    已完成 --> 已取消 : 取消(商城、乐园)

    已完成 --> 已核验 : 核验(商城、乐园)

    已核验 --> 已取消 : 取消(商城、乐园)

    已核验 --> [*]

    已取消 --> [*]

}

@enduml